export const initialRows = [
    {
      id: 1,
      outcome: "SO1: Analyze a computing problem",
      source: "CSC310",
      pcs: "PC1.3",
      byblosSemester: "Fall 2023",
      byblosReceived: "Yes",
      beirutSemester: "Spring 2024",
      beirutReceived: "Yes",
    },
    {
        id: 2,
        outcome: "SO1: Analyze a computing problem",
        source: "CSC310",
        pcs: "PC1.3",
        byblosSemester: "Fall 2023",
        byblosReceived: "Yes",
        beirutSemester: "Spring 2024",
        beirutReceived: "Yes",
      },
      {
        id: 3,
        outcome: "SO1: Analyze a computing problem",
        source: "CSC310",
        pcs: "PC1.3",
        byblosSemester: "Fall 2023",
        byblosReceived: "Yes",
        beirutSemester: "Spring 2024",
        beirutReceived: "Yes",
      },
      {
        id: 4,
        outcome: "SO1: Analyze a computing problem",
        source: "CSC310",
        pcs: "PC1.3",
        byblosSemester: "Fall 2023",
        byblosReceived: "Yes",
        beirutSemester: "Spring 2024",
        beirutReceived: "Yes",
      },
      {
        id: 5,
        outcome: "SO2: Analyze a computing problem",
        source: "CSC310",
        pcs: "PC1.3",
        byblosSemester: "Fall 2023",
        byblosReceived: "Yes",
        beirutSemester: "Spring 2024",
        beirutReceived: "Yes",
      },
  ];
  